Crie as tabelas indicadas em ModeloBD.png
1 - Carregar os dados dos arquivos nas respectivas tabelas 
2 - Quantos estudantes obtiveram média acima de 83.5 ? 
3 - Faça uma consulta que retorne os cursos dados ordenados em "ordem" alfabética. 
4 - Faça uma consulta que retorne o nome de todas as pessoas cujo o último nome termina com "ez"
5 - Quantos estudantes precisaram de 3 tentativas para serem aprovados 

6 - Usando uma lógica condicional retorne : Id do aluno, nota, aprovado ou reprovado. Aprovado se nota >= 70.0 
  Dica: Fazer conforme o exemplo ### Using Conditional Logic in a SELECT Statement ####  do notebook 


7 - Realizar uma consulta que retorne os nomes dos cursos cuja a média obtida (AVG) pelo alunos foi maior ou igual 75.0  

8 - Realizar uma consulta que retorne os email dos alunos que cursaram 3 vezes um mesmo curso 

9 -  (DESAFIO) Realizar uma consulta que retorne os nomes dos professores mais carrascos - isto é - aqueles cujo o número de alunos reprovados (média menor que 70.0) foi maior do que de
 alunos aprovados.


10 - Ache o PersonID dos estudantes que estão matriculados em mais de 3 curso. 

11 - Ache o PersonID  dos estudantes que estão matriculados em todos os cursos. 

12 - Ache o nome e nota média de cada curso.

Crie as tabelas indicadas em ModeloBD.png

In [38]:
### importa os dados e criar um objeto com python que conecta o banco de dados com o SQL
import sqlite3
object = sqlite3.connect('tarefa_01')

In [39]:
### objeto que vai executar

cursor = object.cursor()

In [40]:
### habilitando dentro do database tarefa_01 as chaves estrangeiras
cursor.execute("PRAGMA PersonId = ON").fetchall()
cursor.execute("PRAGMA StudentId = ON").fetchall()
cursor.execute("PRAGMA CouserId = ON").fetchall()

[]

In [41]:
### Criando as tabelas que irão receber as informações

Person_table = """ CREATE TABLE IF NOT EXISTS Person (
                            PersonId integer PRIMARY KEY,
                            First_name text NOT NULL,
                            Middlellnitial text,
                            LastName text,
                            DateOfBirth text
                            );"""

In [42]:
####verificar se a tabela foi criada certa. Primeiro executa o objeto
cursor.execute(Person_table)
cursor.execute('PRAGMA table_info (Person)').fetchall()
###explicar cada coisa

[(0, 'PersonId', 'INTEGER', 0, None, 1),
 (1, 'First_name', 'TEXT', 1, None, 0),
 (2, 'Middlellnitial', 'TEXT', 0, None, 0),
 (3, 'LastName', 'TEXT', 0, None, 0),
 (4, 'DateOfBirth', 'TEXT', 0, None, 0)]

In [43]:
Student_table = """ CREATE TABLE IF NOT EXISTS Student (
                StudentId integer PRIMARY KEY,
                PersonId integer INT REFERENCES Person (PersonId),
                Email text);"""

In [44]:
cursor.execute(Student_table)
cursor.execute('PRAGMA table_info (Student)').fetchall()

[(0, 'StudentId', 'INTEGER', 0, None, 1),
 (1, 'PersonId', 'integer REFERENCE PersonId', 0, None, 0),
 (2, 'Email', 'TEXT', 0, None, 0)]

In [45]:
Course_table = """ CREATE TABLE IF NOT EXISTS Course (
                CourseId integer PRIMARY KEY,
                Name text,
                Teacher text);"""

In [46]:
cursor.execute(Course_table)
cursor.execute('PRAGMA table_info(Course)').fetchall()

[(0, 'CourseId', 'TEXT', 0, None, 1),
 (1, 'Name', 'TEXT', 0, None, 0),
 (2, 'Teacher', 'TEXT', 0, None, 0)]

In [47]:
Credit_table = """ CREATE TABLE IF NOT EXISTS Credit (
                StudentId INT REFERENCES Student (StudentId),
                CourseId INT REFERENCES Course (CourseId),
                Grade FLOAT,
                Attempt integer);"""

In [48]:
cursor.execute(Credit_table)
cursor.execute('PRAGMA table_info(Credit)').fetchall()
### primeiro é o numero da coluna, segundo o nome, o tipo, indica se é NOT NULL, como não é então é 0, o próximo não tiver for the full é none, e a ultima é se eh chave primaria ou não. Se chave primaria é 1

[(0, 'StudentId', 'INTEGER', 0, None, 0),
 (1, 'CourseId', 'TEXT', 0, None, 0),
 (2, 'Grade', 'float', 0, None, 0),
 (3, 'Attempt', 'INTEGER', 0, None, 0)]

1 - Carregar os dados dos arquivos nas respectivas tabelas

In [49]:
### Fazendo o uploading do arquivo

Person_arquivo = "C:/Users/laiss/OneDrive/Arquivos/analista de dados/phyton para processamento de dados/SQL/SamplePersonData.txt"

with open(Person_arquivo,'r') as file1:
    for line in file1:
        valor1 = line.split(",")
        insert1 = f''' INSERT INTO Person
                                (PersonId, First_name, Middlellnitial, LastName, DateOfBirth)
                                VALUES ({valor1[0]}, "{valor1[1]}", "{valor1[2]}","{valor1[3]}","{valor1[4]}")
                                ;'''
object.commit()

In [50]:
cursor.execute('SELECT * FROM Person').fetchall()

[(1, 'Adele', 'S', 'Rosales', '1984-05-05'),
 (2, 'Justus', 'Z', 'Gomez', '2007-04-06'),
 (3, 'Isiah', 'Z', 'Warner', '1992-06-04'),
 (4, 'Erica', 'L', 'Campos', '1994-05-14'),
 (5, 'Desmond', 'W', 'Valdez', '1996-11-19'),
 (6, 'Arnav', 'R', 'Powers', '2008-05-12'),
 (7, 'Ali', 'G', 'Bowen', '1995-03-11'),
 (8, 'Malaya', 'U', 'Burgess', '1984-09-14'),
 (9, 'Haleigh', 'M', 'Hopper', '1997-07-24'),
 (10, 'Corey', 'Y', 'Mcclure', '1997-05-15'),
 (11, 'Jacob', 'P', 'Dotson', '2008-01-02'),
 (12, 'Aden', 'F', 'Petty', '2007-12-02'),
 (13, 'Theodore', 'L', 'Acosta', '1991-07-15'),
 (14, 'Harley', 'H', 'Manning', '1996-03-15'),
 (15, 'Karma', 'N', 'Guerrero', '2005-02-18'),
 (16, 'Legend', 'L', 'Olson', '1990-03-13'),
 (17, 'Issac', 'A', 'Lee', '2008-03-09'),
 (18, 'Maggie', 'I', 'York', '1984-02-04'),
 (19, 'Amare', 'A', 'Hernandez', '2000-09-17'),
 (20, 'Lilah', 'W', 'Abbott', '1998-05-24'),
 (21, 'Eugene', 'R', 'Mathis', '1997-02-04'),
 (22, 'Miya', 'K', 'Warren', '1981-03-15'),
 (23, 'Muhammad', 'R', 'Scott', '1996-11-06'),
 (24, 'Erik', 'Z', 'Mcmillan', '2005-12-21'),
 (25, 'Valentino', 'P', 'Christensen', '1991-01-10'),
 (26, 'Trystan', 'P', 'Barker', '2001-08-07'),
 (27, 'Marcus', 'M', 'Owens', '2003-08-25'),
 (28, 'Aylin', 'C', 'Joyner', '2008-07-01'),
 (29, 'George', 'U', 'Richardson', '1996-04-13'),
 (30, 'Scott', 'M', 'Wooten', '2008-08-02'),
 (31, 'Monica', 'C', 'Roth', '1997-03-20'),
 (32, 'Noemi', 'K', 'Shelton', '2008-07-15'),
 (33, 'Maliyah', 'M', 'Ramsey', '1996-07-16'),
 (34, 'Waylon', 'P', 'Bradley', '1986-11-14'),
 (35, 'Laura', 'G', 'Herrera', '1988-05-12'),
 (36, 'Lyric', 'S', 'Horton', '2008-10-24'),
 (37, 'Deandre', 'F', 'Hopper', '2007-03-31'),
 (38, 'Keyon', 'P', 'Hensley', '2005-03-11'),
 (39, 'Luna', 'Y', 'Chan', '2003-03-14'),
 (40, 'Arlo', 'T', 'Martin', '1987-11-03'),
 (41, 'Finley', 'P', 'Saunders', '1989-07-03'),
 (42, 'Lucas', 'I', 'Ball', '1982-11-21'),
 (43, 'Carla', 'A', 'Hill', '1986-05-29'),
 (44, 'Kara', 'G', 'Gould', '2000-05-07'),
 (45, 'Jovani', 'H', 'Heath', '1986-07-01'),
 (46, 'Liam', 'S', 'Parks', '1991-01-30'),
 (47, 'Jeramiah', 'M', 'Stanley', '1985-12-14'),
 (48, 'Armani', 'D', 'Hensley', '1991-05-09'),
 (49, 'Kolton', 'Q', 'Hopkins', '2005-02-08'),
 (50, 'Porter', 'U', 'Sears', '1997-04-09'),
 (51, 'Jerome', 'Y', 'Jarvis', '1983-03-14'),
 (52, 'Broderick', 'W', 'Terry', '2005-12-25'),
 (53, 'Drake', 'X', 'Hammond', '2007-06-13'),
 (54, 'Hassan', 'T', 'Carney', '2003-11-05'),
 (55, 'Lara', 'X', 'Torres', '2006-04-23'),
 (56, 'Sharon', 'X', 'Jefferson', '1992-04-25'),
 (57, 'Jasmin', 'E', 'Cummings', '1988-08-02'),
 (58, 'Rhys', 'Q', 'Herman', '1988-03-05'),
 (59, 'Eden', 'M', 'Meyers', '1986-04-11'),
 (60, 'Eddie', 'E', 'Clements', '1994-11-21'),
 (61, 'Quincy', 'H', 'Goodwin', '2004-09-30'),
 (62, 'Samiyah', 'I', 'Ortega', '2007-08-23'),
 (63, 'Devon', 'P', 'Garcia', '1995-09-10'),
 (64, 'Lillie', 'F', 'Hanson', '2005-03-19'),
 (65, 'Evangeline', 'R', 'Mccall', '1986-05-30'),
 (66, 'Freddy', 'N', 'Coleman', '2002-10-20'),
 (67, 'Madden', 'D', 'Cross', '1986-07-18'),
 (68, 'Damaris', 'O', 'Mckay', '2007-09-02'),
 (69, 'Iliana', 'V', 'Blankenship', '1995-09-22'),
 (70, 'Julieta', 'E', 'Wilder', '2005-07-08'),
 (71, 'Selah', 'L', 'Mcpherson', '2008-06-01'),
 (72, 'Jermaine', 'S', 'Kinney', '2006-08-06'),
 (73, 'Haley', 'R', 'Smith', '1980-04-04'),
 (74, 'Anna', 'Q', 'Cote', '1989-02-22'),
 (75, 'Brielle', 'Q', 'Wilder', '2003-04-18'),
 (76, 'Alejandra', 'H', 'Vaughan', '1982-09-13'),
 (77, 'Deegan', 'E', 'Keith', '1987-09-01'),
 (78, 'Joselyn', 'O', 'Randolph', '2000-02-14'),
 (79, 'Brett', 'T', 'Spence', '2000-03-26'),
 (80, 'Iker', 'Y', 'Owens', '2007-07-18'),
 (81, 'Cherish', 'X', 'Monroe', '1989-12-10'),
 (82, 'Max', 'H', 'Ballard', '1997-10-13'),
 (83, 'Cali', 'B', 'Jefferson', '1999-07-14'),
 (84, 'Analia', 'N', 'Patterson', '1989-05-31'),
 (85, 'Sidney', 'T', 'Kerr', '1991-03-06'),
 (86, 'Princeton', 'N', 'Mcintyre', '1984-07-02'),
 (87, 'Reuben', 'I', 'Galloway', '2001-08-01'),
 (88, 'Jean', 'H', 'Walters', '1998-04-12'),
 (89, 'Josiah', 'W', 'Roberson', '2001-11-14'),
 (90, 'Samantha', 'N', 'Dennis', '1983-10-05'),
 (91, 'Juniper', 'C', 'Patton', '1988-09-23'),
 (92, 'Macy', 'M', 'Hopper', '1996-10-12'),
 (93, 'Fernanda', 'B', 'Williamson', '1990-11-29'),
 (94, 'Jairo', 'O', 'Mcintyre', '1990-12-09'),
 (95, 'Nicole', 'D', 'Kirby', '1994-02-26'),
 (96, 'Pedro', 'P', 'Singleton', '1985-01-17'),
 (97, 'Brendan', 'I', 'Foley', '2001-08-28'),
 (98, 'Delaney', 'Z', 'Mathews', '1987-03-18'),
 (99, 'Shane', 'Y', 'Casey', '2003-02-19'),
 (100, 'Nathanael', 'B', 'Morrow', '2006-03-28'),
 (101, 'Jensen', 'L', 'Mccall', '2003-02-06'),
 (102, 'Maximo', 'R', 'Reid', '2000-09-03'),
 (103, 'Krystal', 'X', 'Buckner', '1985-07-26'),
 (104, 'Bennett', 'K', 'Green', '2008-07-07'),
 (105, 'Kenny', 'N', 'Noel', '1992-03-28'),
 (106, 'Scarlett', 'L', 'Wooten', '2001-06-06'),
 (107, 'Carson', 'X', 'Calderon', '1999-02-19'),
 (108, 'Cindy', 'K', 'Meyers', '2000-09-18'),
 (109, 'Juan', 'Z', 'Leach', '1980-05-20'),
 (110, 'Damaris', 'V', 'Clayton', '1992-12-24'),
 (111, 'Adeline', 'S', 'Solomon', '1995-03-08'),
 (112, 'Chad', 'F', 'Burris', '1986-02-28'),
 (113, 'Joshua', 'I', 'Mckenzie', '1984-08-14'),
 (114, 'Alani', 'C', 'Harmon', '2006-03-06'),
 (115, 'Genevieve', 'J', 'Workman', '1984-10-02'),
 (116, 'Casen', 'O', 'Donovan', '1985-12-19'),
 (117, 'Toby', 'N', 'Reid', '2008-05-09'),
 (118, 'Jaida', 'E', 'Martinez', '2000-11-06'),
 (119, 'Faith', 'M', 'Walker', '1992-08-10'),
 (120, 'Samara', 'L', 'Acosta', '1992-05-08'),
 (121, 'Cortez', 'F', 'Hardy', '1995-11-12'),
 (122, 'Mariano', 'G', 'Lyons', '1988-03-24'),
 (123, 'Denise', 'B', 'George', '1984-12-29'),
 (124, 'Kailey', 'Q', 'Hughes', '2003-09-27'),
 (125, 'Aaron', 'S', 'Perez', '1987-02-04'),
 (126, 'Elijah', 'B', 'Padilla', '2001-11-19'),
 (127, 'Eileen', 'I', 'Salazar', '1985-01-21'),
 (128, 'Alonzo', 'M', 'Yates', '1995-11-01'),
 (129, 'Diego', 'B', 'Farrell', '1997-08-17'),
 (130, 'Allan', 'O', 'Lucas', '2004-11-09'),
 (131, 'Nathalie', 'I', 'Houston', '1993-09-29'),
 (132, 'Ashlyn', 'R', 'Weeks', '1982-08-05'),
 (133, 'Alonso', 'F', 'Wall', '2007-09-02'),
 (134, 'Xavier', 'I', 'Schwartz', '1988-03-24'),
 (135, 'Jakob', 'H', 'Chang', '1981-02-21'),
 (136, 'Solomon', 'F', 'Mueller', '1992-12-11'),
 (137, 'Dominic', 'G', 'Mcintyre', '2004-07-31'),
 (138, 'Arlo', 'H', 'Tran', '1980-09-19'),
 (139, 'Alicia', 'Y', 'Vance', '1986-01-10'),
 (140, 'Rayden', 'R', 'Harding', '1996-05-14'),
 (141, 'Colton', 'E', 'Jarvis', '1989-07-13'),
 (142, 'Justin', 'Y', 'Gamble', '2006-05-31'),
 (143, 'Journey', 'L', 'Hodge', '1981-05-08'),
 (144, 'Yamilet', 'D', 'Delgado', '2006-02-16'),
 (145, 'Cullen', 'R', 'Dixon', '1988-11-11'),
 (146, 'Bentley', 'M', 'Sykes', '1998-09-13'),
 (147, 'Ashtyn', 'C', 'Morgan', '2000-07-22'),
 (148, 'Claudia', 'P', 'England', '2001-04-03'),
 (149, 'Saul', 'R', 'Wiley', '1998-10-08'),
 (150, 'Riley', 'P', 'Villarreal', '2004-09-30'),
 (151, 'Ashlynn', 'F', 'Bradley', '1993-04-01'),
 (152, 'Leighton', 'N', 'Holder', '1991-06-20'),
 (153, 'Masen', 'V', 'Hamilton', '2007-03-30'),
 (154, 'Frances', 'C', 'Sampson', '1997-07-04'),
 (155, 'Kareem', 'J', 'Wolfe', '1999-05-22'),
 (156, 'Ariel', 'E', 'Kramer', '1983-03-10'),
 (157, 'Will', 'K', 'Underwood', '1986-08-24'),
 (158, 'Case', 'B', 'Salinas', '1989-10-28'),
 (159, 'Elyse', 'B', 'Rowe', '1989-02-18'),
 (160, 'Zavier', 'Z', 'Mercado', '1997-04-16'),
 (161, 'Ivy', 'H', 'Black', '2002-01-25'),
 (162, 'Jason', 'C', 'Hubbard', '2001-07-29'),
 (163, 'Leighton', 'L', 'Richard', '1991-05-20'),
 (164, 'Payton', 'D', 'Vinson', '1991-10-01'),
 (165, 'Carter', 'I', 'Cervantes', '2004-04-04'),
 (166, 'Hannah', 'Q', 'Dalton', '2002-08-19'),
 (167, 'Jaydon', 'L', 'Jarvis', '2004-02-06'),
 (168, 'Bruno', 'F', 'Warner', '1984-03-07'),
 (169, 'Chaim', 'B', 'Carr', '2004-08-21'),
 (170, 'Elin', 'I', 'Bryan', '1981-07-06'),
 (171, 'Mikayla', 'P', 'Cotton', '1980-10-23'),
 (172, 'Angela', 'A', 'Mcconnell', '1987-12-24'),
 (173, 'Moses', 'U', 'Winters', '1992-08-23'),
 (174, 'Declan', 'X', 'Jarvis', '1987-04-10'),
 (175, 'Rayne', 'L', 'Glover', '1991-11-14'),
 (176, 'Bennett', 'B', 'Vega', '1992-07-07'),
 (177, 'Elizabeth', 'R', 'Cross', '1999-04-28'),
 (178, 'Krystal', 'V', 'Mendoza', '1984-11-06'),
 (179, 'Raven', 'F', 'Mcfadden', '2003-02-09'),
 (180, 'Jerimiah', 'V', 'Russell', '1982-11-18'),
 (181, 'Carolina', 'H', 'Stuart', '2008-11-17'),
 (182, 'Linda', 'V', 'Mccall', '2004-11-04'),
 (183, 'Braden', 'Z', 'Collins', '1985-05-21'),
 (184, 'Danica', 'H', 'Rhodes', '1985-06-29'),
 (185, 'Raul', 'Y', 'Berg', '1998-12-19'),
 (186, 'Livia', 'J', 'Bishop', '1992-04-25'),
 (187, 'Anabella', 'J', 'Pierce', '2001-02-23'),
 (188, 'Meadow', 'E', 'Fields', '1980-08-02'),
 (189, 'Ryann', 'M', 'Snider', '1989-10-13'),
 (190, 'Morgan', 'N', 'Cantu', '1987-08-08'),
 (191, 'Heath', 'N', 'Wilkins', '1993-08-18'),
 (192, 'Liv', 'O', 'Maxwell', '1980-12-26'),
 (193, 'Xander', 'P', 'Romero', '1995-08-06'),
 (194, 'Moses', 'Z', 'Mcclain', '2003-02-01'),
 (195, 'Seamus', 'R', 'Lawson', '1998-06-03'),
 (196, 'Jaelyn', 'D', 'Sullivan', '1992-08-22'),
 (197, 'Dustin', 'G', 'Joyce', '1992-11-21'),
 (198, 'Hayleigh', 'A', 'Barrera', '1995-09-11'),
 (199, 'Aleena', 'V', 'Owen', '1998-11-25'),
 (200, 'Bryson', 'S', 'Miller', '1986-04-26'),
 (201, 'Taryn', 'D', 'Garza', '2008-04-26'),
 (202, 'Gwyneth', 'Y', 'Lowe', '2006-02-19'),
 (203, 'Raphael', 'J', 'Mcfadden', '1990-05-16'),
 (204, 'Julieta', 'C', 'David', '2000-05-19'),
 (205, 'Lennon', 'D', 'Sparks', '1994-09-22'),
 (206, 'Emery', 'X', 'Vega', '1986-07-07'),
 (207, 'Iliana', 'N', 'Cooke', '2004-10-02'),
 (208, 'Talon', 'K', 'Logan', '1981-11-17'),
 (209, 'Louis', 'F', 'Beck', '1983-06-18'),
 (210, 'Trace', 'V', 'Randolph', '1992-04-20'),
 (211, 'Samson', 'K', 'Tanner', '2008-06-23'),
 (212, 'Troy', 'O', 'Stephenson', '1996-12-13'),
 (213, 'Jordyn', 'W', 'Pitts', '1987-10-04'),
 (214, 'Judith', 'J', 'Rowland', '2002-10-28'),
 (215, 'Zariah', 'L', 'Short', '1988-05-22'),
 (216, 'Brynlee', 'R', 'Hebert', '1982-06-05'),
 (217, 'Maurice', 'E', 'Rosario', '2005-06-21'),
 (218, 'Heidi', 'Y', 'Simmons', '2007-09-01'),
 (219, 'Lindsay', 'H', 'Church', '1989-07-21'),
 (220, 'Julissa', 'F', 'Harding', '2007-12-11'),
 (221, 'Sophie', 'V', 'Mclaughlin', '1998-08-24'),
 (222, 'Hugh', 'M', 'Lang', '2007-09-24'),
 (223, 'Ismael', 'J', 'Gillespie', '1998-09-04'),
 (224, 'Eli', 'U', 'Vance', '2002-10-21'),
 (225, 'Yareli', 'E', 'George', '2000-05-16'),
 (226, 'Sterling', 'D', 'Camacho', '1989-10-15'),
 (227, 'Jamie', 'E', 'Hutchinson', '1986-03-13'),
 (228, 'Branson', 'B', 'Wilson', '1986-11-17'),
 (229, 'Bennett', 'P', 'Hull', '1995-12-24'),
 (230, 'Kailynn', 'E', 'Rush', '1985-12-14'),
 (231, 'Micah', 'P', 'Browning', '1998-11-25'),
 (232, 'Dean', 'B', 'Shannon', '1994-08-02'),
 (233, 'Kaylynn', 'H', 'Wall', '1998-02-20'),
 (234, 'Vincenzo', 'N', 'Floyd', '2008-04-29'),
 (235, 'Princess', 'D', 'Klein', '2006-04-01'),
 (236, 'Gavin', 'W', 'Conrad', '1983-03-28'),
 (237, 'Brendan', 'K', 'Leblanc', '2007-09-25'),
 (238, 'Krystal', 'O', 'Gates', '1992-01-15'),
 (239, 'Triston', 'Z', 'Tanner', '2001-10-13'),
 (240, 'Danny', 'V', 'Dunn', '2002-06-08'),
 (241, 'Janiya', 'K', 'Flowers', '1995-03-10'),
 (242, 'Catalina', 'V', 'Robbins', '1997-12-04'),
 (243, 'Jadyn', 'O', 'Bradford', '1992-07-27'),
 (244, 'Isai', 'L', 'Dunn', '1984-05-08'),
 (245, 'Ashton', 'J', 'Smith', '1980-07-30'),
 (246, 'Madalyn', 'Q', 'Giles', '1997-01-10'),
 (247, 'Heaven', 'J', 'Stone', '1984-09-23'),
 (248, 'Lilah', 'A', 'Witt', '2004-09-05'),
 (249, 'Joy', 'A', 'Molina', '1994-08-03'),
 (250, 'Journey', 'T', 'Campos', '1999-04-11'),
 (251, 'Madden', 'G', 'Bryant', '2006-10-04'),
 (252, 'Hugh', 'D', 'Bryant', '1993-04-10'),
 (253, 'Reuben', 'B', 'Vinson', '1994-03-21'),
 (254, 'Corban', 'E', 'Flores', '2002-06-23'),
 (255, 'Danny', 'V', 'Montoya', '2000-08-17'),
 (256, 'Katie', 'X', 'Miller', '2004-07-18'),
 (257, 'Journee', 'A', 'Ross', '1989-05-29'),
 (258, 'Reed', 'P', 'Sheppard', '2008-12-03'),
 (259, 'Jerimiah', 'S', 'Galloway', '1998-10-19'),
 (260, 'Gauge', 'B', 'Griffith', '2006-06-08'),
 (261, 'Sariyah', 'A', 'Hanson', '2002-01-27'),
 (262, 'Tessa', 'T', 'Scott', '1983-01-06'),
 (263, 'Kristian', 'C', 'Davidson', '1982-05-24'),
 (264, 'Maritza', 'R', 'Roman', '1985-04-24'),
 (265, 'Aiyana', 'O', 'Koch', '1996-12-24'),
 (266, 'Gunner', 'C', 'Grant', '2000-06-08'),
 (267, 'Haley', 'P', 'Fletcher', '1996-05-28'),
 (268, 'Amir', 'Z', 'Molina', '1984-12-04'),
 (269, 'Remington', 'X', 'Goodwin', '1988-04-10'),
 (270, 'Julian', 'L', 'Cannon', '2001-04-01'),
 (271, 'Sariah', 'O', 'Downs', '2002-01-10'),
 (272, 'Malaya', 'M', 'Dalton', '2006-04-07'),
 (273, 'Isaiah', 'P', 'Hester', '1996-05-24'),
 (274, 'Genesis', 'K', 'Nixon', '1994-11-21'),
 (275, 'Raven', 'G', 'Byrd', '1982-05-13'),
 (276, 'Melanie', 'O', 'Cantu', '1998-08-07'),
 (277, 'Kaylee', 'L', 'Bridges', '2003-06-14'),
 (278, 'Zaniyah', 'G', 'Oconnor', '1992-06-26'),
 (279, 'Emmalee', 'Z', 'Franklin', '2003-03-16'),
 (280, 'Adelina', 'Q', 'Anderson', '2002-11-18'),
 (281, 'Darryl', 'D', 'Lynn', '1997-10-19'),
 (282, 'Jaron', 'I', 'Lindsey', '1988-01-02'),
 (283, 'Danny', 'L', 'Mccoy', '2005-10-06'),
 (284, 'Kylie', 'N', 'Walters', '1988-11-20'),
 (285, 'Mariyah', 'S', 'Richard', '2007-12-12'),
 (286, 'Jaylin', 'G', 'Perkins', '1980-05-28'),
 (287, 'Mason', 'V', 'Parker', '2004-02-11'),
 (288, 'Roselyn', 'X', 'Tyler', '1981-09-22'),
 (289, 'Kylee', 'A', 'Rosario', '1982-03-04'),
 (290, 'Leonel', 'W', 'Joseph', '1983-08-10'),
 (291, 'Annabell', 'K', 'Andrews', '1999-01-12'),
 (292, 'Ana', 'J', 'Potter', '1992-11-24'),
 (293, 'Leonardo', 'B', 'Mayer', '1997-07-02'),
 (294, 'Jonah', 'E', 'Morton', '1980-05-18'),
 (295, 'Giovanna', 'B', 'Jacobs', '1990-09-12'),
 (296, 'Keegan', 'F', 'Griffith', '1996-01-01'),
 (297, 'Meghan', 'A', 'Berger', '1993-05-16'),
 (298, 'Landen', 'I', 'Huber', '1983-05-02'),
 (299, 'Warren', 'K', 'Witt', '2002-04-13'),
 (300, 'Diana', 'F', 'Hardy', '2008-05-05'),
 (301, 'Maria', 'G', 'Crawford', '1981-09-20'),
 (302, 'Maddison', 'I', 'Watson', '1997-02-11'),
 (303, 'Griffin', 'P', 'Jefferson', '1987-05-06'),
 (304, 'Bridger', 'M', 'Frye', '1999-08-12'),
 (305, 'Josiah', 'P', 'Sloan', '1989-12-31'),
 (306, 'Jaiden', 'X', 'Molina', '1998-08-08'),
 (307, 'Kendall', 'L', 'Colon', '1987-10-10'),
 (308, 'Harper', 'S', 'Guthrie', '1993-05-09'),
 (309, 'Bruno', 'N', 'Rowe', '1997-09-18'),
 (310, 'Lamar', 'Q', 'Frost', '1981-12-01'),
 (311, 'Kevin', 'W', 'Lewis', '1980-02-04'),
 (312, 'Kai', 'C', 'Sloan', '2008-03-11'),
 (313, 'Simone', 'M', 'Coleman', '2003-12-18'),
 (314, 'Marlene', 'T', 'Blanchard', '1980-09-30'),
 (315, 'Rowan', 'P', 'Lawson', '1996-10-18'),
 (316, 'Ava', 'H', 'Velez', '1996-08-13'),
 (317, 'Noemi', 'Z', 'Griffin', '1985-12-25'),
 (318, 'Bree', 'O', 'Tyson', '1980-08-24'),
 (319, 'Sloane', 'T', 'Mcdaniel', '2000-01-12'),
 (320, 'Johnny', 'Q', 'Orr', '1994-02-02'),
 (321, 'Irene', 'Z', 'Newton', '1998-03-16'),
 (322, 'Emily', 'T', 'Sweet', '2003-09-19'),
 (323, 'Presley', 'I', 'Moore', '2000-02-16'),
 (324, 'Jaida', 'X', 'Kirk', '1984-05-08'),
 (325, 'Cale', 'B', 'Rutledge', '1994-07-17'),
 (326, 'Kyson', 'U', 'Lynn', '2006-10-13'),
 (327, 'Alexis', 'I', 'Mcmillan', '1986-04-07'),
 (328, 'Isis', 'L', 'Lara', '2005-03-08'),
 (329, 'Remington', 'A', 'Warren', '2008-08-04'),
 (330, 'Leland', 'Y', 'Kennedy', '1992-12-22'),
 (331, 'Messiah', 'I', 'Mullen', '2008-08-25'),
 (332, 'Sara', 'B', 'Noble', '2008-06-08'),
 (333, 'Briella', 'H', 'Hurley', '1988-12-15'),
 (334, 'Winston', 'Z', 'Hutchinson', '1988-09-16'),
 (335, 'Dane', 'T', 'Atkinson', '1982-12-04'),
 (336, 'Amare', 'J', 'Shaffer', '1997-02-16'),
 (337, 'Jaron', 'A', 'Maldonado', '1989-08-25'),
 (338, 'Mohammad', 'J', 'Dickson', '2000-01-18'),
 (339, 'Alessandro', 'H', 'Bird', '1986-08-06'),
 (340, 'Abigail', 'H', 'Witt', '2003-06-29'),
 (341, 'Monica', 'Q', 'Cantu', '1997-10-18'),
 (342, 'Everett', 'P', 'Zimmerman', '2000-02-29'),
 (343, 'Audriana', 'G', 'Miranda', '2003-06-09'),
 (344, 'Tatiana', 'N', 'Noble', '1982-07-14'),
 (345, 'Nahla', 'C', 'Johnston', '1999-08-15'),
 (346, 'Janiyah', 'O', 'Welch', '1996-02-15'),
 (347, 'Blake', 'U', 'Keller', '1995-10-23'),
 (348, 'Aaden', 'Y', 'West', '2005-08-23'),
 (349, 'Jaylene', 'R', 'Delacruz', '1999-01-10'),
 (350, 'Camila', 'P', 'Sanders', '1995-06-09'),
 (351, 'George', 'M', 'Pena', '2007-06-06'),
 (352, 'Branden', 'S', 'Langley', '1989-10-06'),
 (353, 'Cortez', 'U', 'Davidson', '2000-06-16'),
 (354, 'Gage', 'Q', 'Wilder', '1991-04-20'),
 (355, 'Londyn', 'I', 'Wyatt', '1986-03-07'),
 (356, 'Lennox', 'P', 'Graves', '2007-11-12'),
 (357, 'Sonia', 'Z', 'Dickson', '1980-10-06'),
 (358, 'Finnegan', 'G', 'Becker', '1981-09-16'),
 (359, 'Juliette', 'L', 'Parrish', '2002-05-19'),
 (360, 'Jamari', 'E', 'Barrera', '1994-05-18'),
 (361, 'Kennedy', 'V', 'Harris', '1988-10-22'),
 (362, 'Giada', 'C', 'Fernandez', '1986-08-10'),
 (363, 'Damaris', 'V', 'Norris', '1990-09-18'),
 (364, 'Maximiliano', 'A', 'Sawyer', '1993-12-14'),
 (365, 'Norah', 'Z', 'Sloan', '1999-03-10'),
 (366, 'Savanna', 'Q', 'Cabrera', '1994-06-02'),
 (367, 'Caroline', 'B', 'Le', '1980-09-16'),
 (368, 'Cameron', 'V', 'Short', '2001-08-22'),
 (369, 'Andre', 'M', 'Mcintyre', '1988-01-24'),
 (370, 'Elianna', 'W', 'Howard', '2001-06-12'),
 (371, 'Deangelo', 'T', 'Rose', '1995-08-20'),
 (372, 'Elisa', 'S', 'Thornton', '1993-08-18'),
 (373, 'Iliana', 'N', 'Strickland', '1995-09-28'),
 (374, 'Kaitlynn', 'Q', 'Nieves', '2005-02-20'),
 (375, 'Raelyn', 'C', 'Ruiz', '1989-03-17'),
 (376, 'Chaim', 'S', 'Hodge', '1991-09-08'),
 (377, 'Griffin', 'H', 'Sullivan', '2005-07-05'),
 (378, 'Shelby', 'Z', 'Harper', '1986-07-17'),
 (379, 'Brayan', 'A', 'Castaneda', '1985-09-18'),
 (380, 'Kameron', 'F', 'Morton', '1986-08-31'),
 (381, 'Payton', 'I', 'Vaughn', '1989-09-13'),
 (382, 'Lilia', 'V', 'Nichols', '1983-02-02'),
 (383, 'Ivy', 'L', 'Maynard', '1987-07-30'),
 (384, 'Arian', 'R', 'Burns', '1990-02-18'),
 (385, 'Kyler', 'I', 'Alford', '1988-05-24'),
 (386, 'Charlee', 'N', 'Wallace', '1999-11-30'),
 (387, 'Josue', 'G', 'Martin', '1986-06-16'),
 (388, 'Esteban', 'U', 'Gregory', '2002-11-24'),
 (389, 'Vihaan', 'T', 'Palmer', '1980-12-29'),
 (390, 'Samuel', 'G', 'Yang', '1983-10-18'),
 (391, 'Kaylee', 'S', 'May', '1996-11-18'),
 (392, 'Kellan', 'B', 'Cannon', '1989-01-17'),
 (393, 'Harrison', 'U', 'Hickman', '1990-04-04'),
 (394, 'Kaliyah', 'R', 'Cervantes', '2005-12-11'),
 (395, 'Frankie', 'J', 'Rosales', '1994-12-01'),
 (396, 'Geraldine', 'Y', 'Marsh', '2003-11-29'),
 (397, 'Kylan', 'W', 'Sellers', '1994-02-21'),
 (398, 'Mina', 'G', 'Page', '2003-12-13'),
 (399, 'Journee', 'F', 'Kemp', '1988-08-03'),
 (400, 'June', 'H', 'Hodge', '1997-08-31'),
 (401, 'Joe', 'Y', 'Bonner', '2004-01-23'),
 (402, 'Macie', 'Q', 'Hansen', '2002-11-10'),
 (403, 'Jacey', 'A', 'Randolph', '1983-08-07'),
 (404, 'Natalia', 'V', 'Mcbride', '1988-02-22'),
 (405, 'Madalyn', 'J', 'Ayers', '2005-03-12'),
 (406, 'Eduardo', 'B', 'Chapman', '1993-10-29'),
 (407, 'Kendra', 'V', 'Browning', '2000-12-22'),
 (408, 'Aimee', 'H', 'Joseph', '2006-02-15'),
 (409, 'Nevaeh', 'D', 'Gibbs', '1986-04-24'),
 (410, 'Casey', 'V', 'Mann', '1984-12-09'),
 (411, 'Francisco', 'V', 'Love', '2003-07-13'),
 (412, 'Keyon', 'U', 'Richard', '1997-06-13'),
 (413, 'Taylor', 'O', 'Mccormick', '1983-05-07'),
 (414, 'Stephen', 'M', 'Branch', '1980-08-11'),
 (415, 'Emmalyn', 'R', 'Conrad', '1989-05-30'),
 (416, 'Davon', 'D', 'Gould', '1992-03-24'),
 (417, 'Quinten', 'I', 'Maxwell', '1999-03-03'),
 (418, 'Albert', 'Z', 'Burns', '2005-12-15'),
 (419, 'Braylen', 'L', 'Tucker', '2005-08-26'),
 (420, 'Ana', 'Y', 'Hodges', '2005-01-01'),
 (421, 'Shaun', 'R', 'Quinn', '2000-01-19'),
 (422, 'Adrien', 'N', 'Albert', '1988-03-30'),
 (423, 'Raelyn', 'N', 'Davis', '1980-02-18'),
 (424, 'Louis', 'N', 'Ramos', '1981-12-22'),
 (425, 'Rhys', 'X', 'Fischer', '1989-02-25'),
 (426, 'Itzel', 'C', 'Witt', '1985-12-08'),

In [55]:
Student_arquivo = "C:/Users/laiss/OneDrive/Arquivos/analista de dados/phyton para processamento de dados/SQL/SampleStudentData.txt"

with open(Student_arquivo,'r') as file2:
    for liner in file2:
        valor2 = liner.split(",")
        insert2 = f''' INSERT INTO Student
                                (StudentId, PersonId, Email)
                                VALUES ({valor2[0]}, {valor2[1]}, "{valor2[2]}")
                                ;'''
object.commit()

In [56]:
cursor.execute('SELECT * FROM Student').fetchall()

[(1, 1, 'A'),
 (2, 2, 'J'),
 (3, 3, 'I'),
 (4, 4, 'E'),
 (5, 5, 'D'),
 (6, 6, 'A'),
 (7, 7, 'A'),
 (8, 8, 'M'),
 (9, 9, 'H')]

In [53]:
Credit_arquivo = "C:/Users/laiss/OneDrive/Arquivos/analista de dados/phyton para processamento de dados/SQL/SampleCreditData.txt"

with open(Credit_arquivo,'r') as file3:
    for liner in file3:
        valor3 = liner.replace(",","")
        insert3 = f''' INSERT INTO Credit
                                (StudentId, CouserId, Grade, Attempt)
                                VALUES ({valor3[0]}, "{valor3[1]}", {valor3[2]}, {valor3[3]});'''

object.commit()

In [54]:
cursor.execute('SELECT * FROM Credit').fetchall()

[]